# Generated by Django 2.2.5 on 2019-09-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_post_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_2',
        ),
    ]
